// Starter recipe pack: 26 dinner recipes for Danish households.
// Danish recipe ingredient lists adapted from valdemarsro.dk.
// Asian recipes based on common versions of popular dishes.

import type { Recipe } from "./store.js";

export const defaultRecipes: Recipe[] = [
  {
    name: "Frikadeller",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "pork",
    ingredients: [
      {
        name: "Hakket svinekød",
        quantity: "500 g",
        searchTerms: ["hakket svinekød", "svinefars", "fars"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Æg",
        quantity: "1 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Rasp",
        quantity: "3 spsk",
        searchTerms: ["rasp", "brødkrummer"],
        category: "pantry",
      },
      {
        name: "Mælk",
        quantity: "1 dl",
        searchTerms: ["mælk", "letmælk"],
        category: "dairy",
      },
      {
        name: "Salt og peber",
        quantity: "efter smag",
        searchTerms: ["salt", "peber"],
        category: "pantry",
      },
      {
        name: "Smør",
        quantity: "2 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Kartofler",
        quantity: "800 g",
        searchTerms: ["kartofler"],
        category: "produce",
      },
      {
        name: "Persillesovs",
        quantity: "5 dl",
        searchTerms: ["persille", "fløde", "smør"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Spaghetti Bolognese",
    servings: 4,
    complexity: "medium",
    cuisineType: "italian",
    proteinType: "beef",
    ingredients: [
      {
        name: "Hakket oksekød",
        quantity: "500 g",
        searchTerms: ["hakket oksekød", "oksefars"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "2 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Bladselleri",
        quantity: "2 stængler",
        searchTerms: ["bladselleri", "selleri"],
        category: "produce",
      },
      {
        name: "Hakkede tomater",
        quantity: "800 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Tomatpuré",
        quantity: "2 spsk",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Rødvin",
        quantity: "1 dl",
        searchTerms: ["rødvin"],
        category: "drinks",
      },
      {
        name: "Oregano",
        quantity: "1 tsk",
        searchTerms: ["oregano", "tørret oregano"],
        category: "pantry",
      },
      {
        name: "Spaghetti",
        quantity: "400 g",
        searchTerms: ["spaghetti", "pasta"],
        category: "pantry",
      },
      {
        name: "Parmesan",
        quantity: "50 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
      {
        name: "Olivenolie",
        quantity: "2 spsk",
        searchTerms: ["olivenolie"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Chili con Carne",
    servings: 4,
    complexity: "medium",
    cuisineType: "mexican",
    proteinType: "beef",
    ingredients: [
      {
        name: "Hakket oksekød",
        quantity: "500 g",
        searchTerms: ["hakket oksekød", "oksefars"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Rød peberfrugt",
        quantity: "2 stk",
        searchTerms: ["peberfrugt", "rød peberfrugt"],
        category: "produce",
      },
      {
        name: "Kidneybønner",
        quantity: "400 g",
        searchTerms: ["kidneybønner", "bønner"],
        category: "pantry",
      },
      {
        name: "Hakkede tomater",
        quantity: "800 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Tomatpuré",
        quantity: "2 spsk",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Spidskommen",
        quantity: "2 tsk",
        searchTerms: ["spidskommen", "cumin"],
        category: "pantry",
      },
      {
        name: "Chili",
        quantity: "1 tsk",
        searchTerms: ["chili", "chilipulver", "chiliflager"],
        category: "pantry",
      },
      {
        name: "Sød paprika",
        quantity: "1 tsk",
        searchTerms: ["paprika", "sød paprika"],
        category: "pantry",
      },
      {
        name: "Ris",
        quantity: "3 dl",
        searchTerms: ["ris", "basmatiris"],
        category: "pantry",
      },
      {
        name: "Creme fraiche",
        quantity: "1 dl",
        searchTerms: ["creme fraiche"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Brændende Kærlighed",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "pork",
    ingredients: [
      {
        name: "Kartofler",
        quantity: "1 kg",
        searchTerms: ["kartofler"],
        category: "produce",
      },
      {
        name: "Bacon",
        quantity: "250 g",
        searchTerms: ["bacon", "baconskiver"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Smør",
        quantity: "2 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Mælk",
        quantity: "1 dl",
        searchTerms: ["mælk", "letmælk"],
        category: "dairy",
      },
      {
        name: "Syltede rødbeder",
        quantity: "200 g",
        searchTerms: ["syltede rødbeder", "rødbeder"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Kylling i Karry",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingefilet",
        quantity: "400 g",
        searchTerms: ["kyllingefilet", "kyllingebryst"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "1 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Karry",
        quantity: "1 spsk",
        searchTerms: ["karry", "curry"],
        category: "pantry",
      },
      {
        name: "Spidskommen",
        quantity: "1 tsk",
        searchTerms: ["spidskommen", "cumin"],
        category: "pantry",
      },
      {
        name: "Gurkemeje",
        quantity: "0.5 tsk",
        searchTerms: ["gurkemeje"],
        category: "pantry",
      },
      {
        name: "Æble",
        quantity: "2 stk",
        searchTerms: ["æble", "æbler"],
        category: "produce",
      },
      {
        name: "Mælk",
        quantity: "4 dl",
        searchTerms: ["mælk", "letmælk"],
        category: "dairy",
      },
      {
        name: "Piskefløde",
        quantity: "0.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Maizena",
        quantity: "2 spsk",
        searchTerms: ["maizena", "majsstivelse"],
        category: "pantry",
      },
      {
        name: "Basmatiris",
        quantity: "3 dl",
        searchTerms: ["basmatiris", "ris"],
        category: "pantry",
      },
      {
        name: "Banan",
        quantity: "1 stk",
        searchTerms: ["banan", "bananer"],
        category: "produce",
      },
      {
        name: "Kokosmel",
        quantity: "1 dl",
        searchTerms: ["kokosmel"],
        category: "pantry",
      },
      {
        name: "Kyllingebouillon",
        quantity: "2 dl",
        searchTerms: ["kyllingebouillon", "bouillon"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Laks i fad",
    servings: 4,
    complexity: "medium",
    cuisineType: "danish",
    proteinType: "fish",
    ingredients: [
      {
        name: "Laks",
        quantity: "500 g",
        searchTerms: ["laks", "laksefilet"],
        category: "meat",
      },
      {
        name: "Kartofler",
        quantity: "600 g",
        searchTerms: ["kartofler"],
        category: "produce",
      },
      {
        name: "Porre",
        quantity: "1 stk",
        searchTerms: ["porre", "porrer"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "3 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Fennikel",
        quantity: "1 stk",
        searchTerms: ["fennikel"],
        category: "produce",
      },
      {
        name: "Spidskål",
        quantity: "400 g",
        searchTerms: ["spidskål", "kål"],
        category: "produce",
      },
      {
        name: "Piskefløde",
        quantity: "1.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1.5 dl",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Hvidvin",
        quantity: "1 dl",
        searchTerms: ["hvidvin"],
        category: "drinks",
      },
      {
        name: "Dijonsennep",
        quantity: "1 tsk",
        searchTerms: ["dijonsennep", "sennep"],
        category: "pantry",
      },
      {
        name: "Citron",
        quantity: "1 stk",
        searchTerms: ["citron"],
        category: "produce",
      },
      {
        name: "Persille",
        quantity: "1 håndfuld",
        searchTerms: ["persille", "frisk persille"],
        category: "produce",
      },
    ],
  },
  {
    name: "Flæskesteg",
    servings: 4,
    complexity: "slow",
    cuisineType: "danish",
    proteinType: "pork",
    ingredients: [
      {
        name: "Svinekam",
        quantity: "1 kg",
        searchTerms: ["svinekam", "flæskesteg"],
        category: "meat",
      },
      {
        name: "Laurbærblade",
        quantity: "8 stk",
        searchTerms: ["laurbærblade", "laurbær"],
        category: "pantry",
      },
      {
        name: "Frisk timian",
        quantity: "4 kviste",
        searchTerms: ["timian", "frisk timian"],
        category: "produce",
      },
      {
        name: "Salt",
        quantity: "efter smag",
        searchTerms: ["salt", "groft salt"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Tomatsuppe",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "vegetarian",
    ingredients: [
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Porre",
        quantity: "1 stk",
        searchTerms: ["porre", "porrer"],
        category: "produce",
      },
      {
        name: "Kartofler",
        quantity: "3 stk",
        searchTerms: ["kartofler"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "3 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Flåede tomater",
        quantity: "1200 g",
        searchTerms: ["flåede tomater", "dåsetomater", "hakkede tomater"],
        category: "pantry",
      },
      {
        name: "Tomatpuré",
        quantity: "100 g",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1 liter",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "0.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Creme fraiche",
        quantity: "1 dl",
        searchTerms: ["creme fraiche"],
        category: "dairy",
      },
      {
        name: "Brødskiver",
        quantity: "8 stk",
        searchTerms: ["brød", "franskbrød", "toastbrød"],
        category: "bakery",
      },
      {
        name: "Mozzarella",
        quantity: "125 g",
        searchTerms: ["mozzarella"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Hakkebøffer med bløde løg",
    servings: 4,
    complexity: "medium",
    cuisineType: "danish",
    proteinType: "beef",
    ingredients: [
      {
        name: "Hakket oksekød",
        quantity: "500 g",
        searchTerms: ["hakket oksekød", "oksefars"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "3 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Champignon",
        quantity: "200 g",
        searchTerms: ["champignon", "svampe"],
        category: "produce",
      },
      {
        name: "Smør",
        quantity: "2 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Piskefløde",
        quantity: "1 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1 dl",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Worcestershiresauce",
        quantity: "1 tsk",
        searchTerms: ["worcestershire", "worcestershiresauce"],
        category: "pantry",
      },
      {
        name: "Maizena",
        quantity: "2 spsk",
        searchTerms: ["maizena", "majsstivelse"],
        category: "pantry",
      },
      {
        name: "Kartofler",
        quantity: "1 kg",
        searchTerms: ["kartofler"],
        category: "produce",
      },
    ],
  },
  {
    name: "Kartoffelsuppe",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "vegetarian",
    ingredients: [
      {
        name: "Kartofler",
        quantity: "1 kg",
        searchTerms: ["kartofler", "bagekartofler"],
        category: "produce",
      },
      {
        name: "Porrer",
        quantity: "3 stk",
        searchTerms: ["porre", "porrer"],
        category: "produce",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1.2 liter",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "0.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Smør",
        quantity: "1 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Rugbrød",
        quantity: "3 skiver",
        searchTerms: ["rugbrød"],
        category: "bakery",
      },
      {
        name: "Bacon",
        quantity: "3 skiver",
        searchTerms: ["bacon", "baconskiver"],
        category: "meat",
      },
    ],
  },
  {
    name: "Lasagne",
    servings: 4,
    complexity: "slow",
    cuisineType: "italian",
    proteinType: "beef",
    ingredients: [
      {
        name: "Hakket oksekød",
        quantity: "400 g",
        searchTerms: ["hakket oksekød", "oksefars"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "4 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "4 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Bladselleri",
        quantity: "5 stængler",
        searchTerms: ["bladselleri", "selleri"],
        category: "produce",
      },
      {
        name: "Squash",
        quantity: "1 stk",
        searchTerms: ["squash", "zucchini"],
        category: "produce",
      },
      {
        name: "Tomatpuré",
        quantity: "50 g",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Hakkede tomater",
        quantity: "800 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Rødvin",
        quantity: "1 dl",
        searchTerms: ["rødvin"],
        category: "drinks",
      },
      {
        name: "Oregano",
        quantity: "2 tsk",
        searchTerms: ["oregano", "tørret oregano"],
        category: "pantry",
      },
      {
        name: "Smør",
        quantity: "2 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Hvedemel",
        quantity: "2 spsk",
        searchTerms: ["hvedemel", "mel"],
        category: "pantry",
      },
      {
        name: "Mælk",
        quantity: "3 dl",
        searchTerms: ["mælk", "sødmælk"],
        category: "dairy",
      },
      {
        name: "Mozzarella",
        quantity: "250 g",
        searchTerms: ["mozzarella"],
        category: "dairy",
      },
      {
        name: "Lasagneplader",
        quantity: "200 g",
        searchTerms: ["lasagneplader", "lasagne pasta"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Tacos med kylling",
    servings: 4,
    complexity: "medium",
    cuisineType: "mexican",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingebryst",
        quantity: "800 g",
        searchTerms: ["kyllingebryst", "kyllingefilet"],
        category: "meat",
      },
      {
        name: "Sød paprika",
        quantity: "1 spsk",
        searchTerms: ["paprika", "sød paprika"],
        category: "pantry",
      },
      {
        name: "Spidskommen",
        quantity: "1 tsk",
        searchTerms: ["spidskommen", "cumin"],
        category: "pantry",
      },
      {
        name: "Hvidløg",
        quantity: "2 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1 dl",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Mango",
        quantity: "1 stk",
        searchTerms: ["mango"],
        category: "produce",
      },
      {
        name: "Avocado",
        quantity: "2 stk",
        searchTerms: ["avocado"],
        category: "produce",
      },
      {
        name: "Lime",
        quantity: "2 stk",
        searchTerms: ["lime"],
        category: "produce",
      },
      {
        name: "Frisk koriander",
        quantity: "1 håndfuld",
        searchTerms: ["koriander", "frisk koriander"],
        category: "produce",
      },
      {
        name: "Majs",
        quantity: "140 g",
        searchTerms: ["majs", "majskerner", "dåsemajs"],
        category: "pantry",
      },
      {
        name: "Rucola",
        quantity: "75 g",
        searchTerms: ["rucola", "rucolasalat"],
        category: "produce",
      },
      {
        name: "Tortilla wraps",
        quantity: "8 stk",
        searchTerms: ["tortilla", "tortilla wraps", "wraps"],
        category: "bakery",
      },
    ],
  },
  {
    name: "Wok med kylling",
    servings: 4,
    complexity: "quick",
    cuisineType: "asian",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingebryst",
        quantity: "400 g",
        searchTerms: ["kyllingebryst", "kyllingefilet"],
        category: "meat",
      },
      {
        name: "Gul karrypasta",
        quantity: "1 spsk",
        searchTerms: ["karrypasta", "curry paste"],
        category: "pantry",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Ingefær",
        quantity: "1 tsk",
        searchTerms: ["ingefær", "frisk ingefær"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Broccoli",
        quantity: "200 g",
        searchTerms: ["broccoli"],
        category: "produce",
      },
      {
        name: "Rød peberfrugt",
        quantity: "1 stk",
        searchTerms: ["peberfrugt", "rød peberfrugt"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "150 g",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Kokosmælk",
        quantity: "400 ml",
        searchTerms: ["kokosmælk"],
        category: "pantry",
      },
      {
        name: "Nudler",
        quantity: "300 g",
        searchTerms: ["nudler", "wok nudler", "risnudler"],
        category: "pantry",
      },
      {
        name: "Spinat",
        quantity: "100 g",
        searchTerms: ["spinat", "baby spinat"],
        category: "produce",
      },
      {
        name: "Sesamolie",
        quantity: "4 spsk",
        searchTerms: ["sesamolie"],
        category: "pantry",
      },
      {
        name: "Forårsløg",
        quantity: "3 stk",
        searchTerms: ["forårsløg", "grønne løg"],
        category: "produce",
      },
      {
        name: "Cashewnødder",
        quantity: "40 g",
        searchTerms: ["cashewnødder", "cashew"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Spaghetti Carbonara",
    servings: 4,
    complexity: "quick",
    cuisineType: "italian",
    proteinType: "pork",
    ingredients: [
      {
        name: "Bacon",
        quantity: "100 g",
        searchTerms: ["bacon", "røget bacon"],
        category: "meat",
      },
      {
        name: "Smør",
        quantity: "1 tsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Piskefløde",
        quantity: "1 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Æg",
        quantity: "3 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Parmesan",
        quantity: "150 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
      {
        name: "Spaghetti",
        quantity: "400 g",
        searchTerms: ["spaghetti", "pasta"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Fiskefilet med remoulade",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "fish",
    ingredients: [
      {
        name: "Rødspættefilet",
        quantity: "8 stk",
        searchTerms: ["rødspættefilet", "fiskefilet", "rødspætte"],
        category: "meat",
      },
      {
        name: "Æg",
        quantity: "2 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Hvedemel",
        quantity: "20 g",
        searchTerms: ["hvedemel", "mel"],
        category: "pantry",
      },
      {
        name: "Smør",
        quantity: "2 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Rugbrød",
        quantity: "8 skiver",
        searchTerms: ["rugbrød"],
        category: "bakery",
      },
      {
        name: "Remoulade",
        quantity: "100 g",
        searchTerms: ["remoulade"],
        category: "pantry",
      },
      {
        name: "Citron",
        quantity: "1 stk",
        searchTerms: ["citron"],
        category: "produce",
      },
    ],
  },
  {
    name: "Biksemad",
    servings: 4,
    complexity: "medium",
    cuisineType: "danish",
    proteinType: "beef",
    ingredients: [
      {
        name: "Kartofler",
        quantity: "1 kg",
        searchTerms: ["kartofler", "kogekartofler"],
        category: "produce",
      },
      {
        name: "Oksekød",
        quantity: "300 g",
        searchTerms: ["oksekød", "oksebøf", "bøf"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Worcestershiresauce",
        quantity: "2 spsk",
        searchTerms: ["worcestershire", "worcestershiresauce"],
        category: "pantry",
      },
      {
        name: "Æg",
        quantity: "4 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Smør",
        quantity: "1 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
      {
        name: "Syltede rødbeder",
        quantity: "100 g",
        searchTerms: ["syltede rødbeder", "rødbeder"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Koteletter i fad",
    servings: 4,
    complexity: "quick",
    cuisineType: "danish",
    proteinType: "pork",
    ingredients: [
      {
        name: "Svinekotelet",
        quantity: "500 g",
        searchTerms: ["kotelet", "svinekotelet", "svinekoteletter"],
        category: "meat",
      },
      {
        name: "Bacon",
        quantity: "100 g",
        searchTerms: ["bacon", "røget bacon"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "2 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Champignon",
        quantity: "500 g",
        searchTerms: ["champignon", "svampe"],
        category: "produce",
      },
      {
        name: "Hakkede tomater",
        quantity: "400 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "2.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Sød paprika",
        quantity: "1 tsk",
        searchTerms: ["paprika", "sød paprika"],
        category: "pantry",
      },
      {
        name: "Timian",
        quantity: "2 tsk",
        searchTerms: ["timian", "tørret timian"],
        category: "pantry",
      },
      {
        name: "Basmatiris",
        quantity: "3 dl",
        searchTerms: ["basmatiris", "ris"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Bagt kylling med ovnkartofler",
    servings: 4,
    complexity: "medium",
    cuisineType: "danish",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingestykker",
        quantity: "1 kg",
        searchTerms: ["kyllingelår", "kyllingebryst", "kylling"],
        category: "meat",
      },
      {
        name: "Kartofler",
        quantity: "800 g",
        searchTerms: ["kartofler", "ovnkartofler", "bagekartofler"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "4 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Timian",
        quantity: "1 tsk",
        searchTerms: ["timian", "tørret timian"],
        category: "pantry",
      },
      {
        name: "Rosmarin",
        quantity: "1 spsk",
        searchTerms: ["rosmarin", "frisk rosmarin"],
        category: "produce",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1 dl",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Smør",
        quantity: "1 spsk",
        searchTerms: ["smør", "lurpak"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Tomatrisotto",
    servings: 4,
    complexity: "medium",
    cuisineType: "italian",
    proteinType: "vegetarian",
    ingredients: [
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Risottoris",
        quantity: "400 g",
        searchTerms: ["risottoris", "arborio ris"],
        category: "pantry",
      },
      {
        name: "Hvidvin",
        quantity: "2 dl",
        searchTerms: ["hvidvin"],
        category: "drinks",
      },
      {
        name: "Hakkede tomater",
        quantity: "400 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Tomatpuré",
        quantity: "25 g",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "9 dl",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Soltørrede tomater",
        quantity: "25 g",
        searchTerms: ["soltørrede tomater"],
        category: "pantry",
      },
      {
        name: "Parmesan",
        quantity: "125 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
      {
        name: "Citron",
        quantity: "0.5 stk",
        searchTerms: ["citron"],
        category: "produce",
      },
      {
        name: "Olivenolie",
        quantity: "1 spsk",
        searchTerms: ["olivenolie"],
        category: "pantry",
      },
      {
        name: "Pesto",
        quantity: "25 g",
        searchTerms: ["pesto", "basilikum pesto"],
        category: "pantry",
      },
      {
        name: "Frisk basilikum",
        quantity: "0.5 håndfuld",
        searchTerms: ["basilikum", "frisk basilikum"],
        category: "produce",
      },
    ],
  },
  {
    name: "Nudelsuppe med kylling",
    servings: 4,
    complexity: "quick",
    cuisineType: "asian",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingefilet",
        quantity: "400 g",
        searchTerms: ["kyllingefilet", "kyllingebryst"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "2 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Ingefær",
        quantity: "2 tsk",
        searchTerms: ["ingefær", "frisk ingefær"],
        category: "produce",
      },
      {
        name: "Rød karrypasta",
        quantity: "2 spsk",
        searchTerms: ["rød karrypasta", "karrypasta"],
        category: "pantry",
      },
      {
        name: "Fiskesauce",
        quantity: "1 spsk",
        searchTerms: ["fiskesauce"],
        category: "pantry",
      },
      {
        name: "Grøntsagsbouillon",
        quantity: "1 liter",
        searchTerms: ["grøntsagsbouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Kokosmælk",
        quantity: "400 ml",
        searchTerms: ["kokosmælk"],
        category: "pantry",
      },
      {
        name: "Gulerødder",
        quantity: "2 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Nudler",
        quantity: "200 g",
        searchTerms: ["nudler", "risnudler", "ægnudler"],
        category: "pantry",
      },
      {
        name: "Spinat",
        quantity: "100 g",
        searchTerms: ["spinat", "baby spinat"],
        category: "produce",
      },
      {
        name: "Lime",
        quantity: "1 stk",
        searchTerms: ["lime"],
        category: "produce",
      },
      {
        name: "Forårsløg",
        quantity: "2 stk",
        searchTerms: ["forårsløg", "grønne løg"],
        category: "produce",
      },
    ],
  },
  {
    name: "Marry Me Chicken",
    servings: 4,
    complexity: "medium",
    cuisineType: "italian",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Kyllingebryst",
        quantity: "4 stk",
        searchTerms: ["kyllingebryst", "kyllingefilet"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "4 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Soltørrede tomater",
        quantity: "75 g",
        searchTerms: ["soltørrede tomater"],
        category: "pantry",
      },
      {
        name: "Oregano",
        quantity: "2 tsk",
        searchTerms: ["oregano", "tørret oregano"],
        category: "pantry",
      },
      {
        name: "Timian",
        quantity: "1 tsk",
        searchTerms: ["timian", "tørret timian"],
        category: "pantry",
      },
      {
        name: "Kyllingebouillon",
        quantity: "2 dl",
        searchTerms: ["kyllingebouillon", "bouillon"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "2.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Tomatpuré",
        quantity: "15 g",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Parmesan",
        quantity: "100 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
      {
        name: "Frisk basilikum",
        quantity: "1 håndfuld",
        searchTerms: ["basilikum", "frisk basilikum"],
        category: "produce",
      },
      {
        name: "Olivenolie",
        quantity: "2 spsk",
        searchTerms: ["olivenolie"],
        category: "pantry",
      },
      {
        name: "Pasta",
        quantity: "400 g",
        searchTerms: ["pasta", "spaghetti", "penne"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Pølsegryde",
    servings: 4,
    complexity: "medium",
    cuisineType: "danish",
    proteinType: "pork",
    ingredients: [
      {
        name: "Wienerpølser",
        quantity: "6 stk",
        searchTerms: ["wienerpølser", "pølser"],
        category: "meat",
      },
      {
        name: "Chorizo",
        quantity: "30 g",
        searchTerms: ["chorizo"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Squash",
        quantity: "300 g",
        searchTerms: ["squash", "zucchini"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "2 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Hakkede tomater",
        quantity: "400 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Tomatpuré",
        quantity: "25 g",
        searchTerms: ["tomatpuré"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "1.5 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Sød paprika",
        quantity: "1 tsk",
        searchTerms: ["paprika", "sød paprika"],
        category: "pantry",
      },
      {
        name: "Oregano",
        quantity: "1 tsk",
        searchTerms: ["oregano", "tørret oregano"],
        category: "pantry",
      },
      {
        name: "Pasta",
        quantity: "400 g",
        searchTerms: ["pasta", "pastaskaller", "fusilli"],
        category: "pantry",
      },
      {
        name: "Parmesan",
        quantity: "50 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Salsiccia Pasta",
    servings: 4,
    complexity: "quick",
    cuisineType: "italian",
    proteinType: "pork",
    ingredients: [
      {
        name: "Salsiccia",
        quantity: "300 g",
        searchTerms: ["salsiccia", "italiensk pølse"],
        category: "meat",
      },
      {
        name: "Løg",
        quantity: "2 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "1 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Timian",
        quantity: "1 tsk",
        searchTerms: ["timian", "tørret timian"],
        category: "pantry",
      },
      {
        name: "Hakkede tomater",
        quantity: "400 g",
        searchTerms: ["hakkede tomater", "dåsetomater"],
        category: "pantry",
      },
      {
        name: "Piskefløde",
        quantity: "1 dl",
        searchTerms: ["piskefløde", "fløde"],
        category: "dairy",
      },
      {
        name: "Pasta",
        quantity: "400 g",
        searchTerms: ["pasta", "spaghetti", "rigatoni"],
        category: "pantry",
      },
      {
        name: "Frisk basilikum",
        quantity: "1 håndfuld",
        searchTerms: ["basilikum", "frisk basilikum"],
        category: "produce",
      },
      {
        name: "Parmesan",
        quantity: "50 g",
        searchTerms: ["parmesan", "parmesanost"],
        category: "dairy",
      },
    ],
  },
  {
    name: "Egg Fried Rice",
    servings: 4,
    complexity: "quick",
    cuisineType: "asian",
    proteinType: "vegetarian",
    ingredients: [
      {
        name: "Jasminris",
        quantity: "4 dl",
        searchTerms: ["jasminris", "ris"],
        category: "pantry",
      },
      {
        name: "Æg",
        quantity: "4 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Forårsløg",
        quantity: "4 stk",
        searchTerms: ["forårsløg", "grønne løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Sojasauce",
        quantity: "2 spsk",
        searchTerms: ["sojasauce", "soja"],
        category: "pantry",
      },
      {
        name: "Sesamolie",
        quantity: "1 spsk",
        searchTerms: ["sesamolie"],
        category: "pantry",
      },
      {
        name: "Neutral olie",
        quantity: "3 spsk",
        searchTerms: ["rapsolie", "solsikkeolie"],
        category: "pantry",
      },
      {
        name: "MSG",
        quantity: "1 tsk",
        searchTerms: ["MSG", "glutamat"],
        category: "pantry",
      },
      {
        name: "Hvid peber",
        quantity: "0.5 tsk",
        searchTerms: ["hvid peber", "peber"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Nasi Goreng",
    servings: 4,
    complexity: "quick",
    cuisineType: "asian",
    proteinType: "chicken",
    ingredients: [
      {
        name: "Jasminris",
        quantity: "4 dl",
        searchTerms: ["jasminris", "ris"],
        category: "pantry",
      },
      {
        name: "Kyllingebryst",
        quantity: "300 g",
        searchTerms: ["kyllingebryst", "kyllingefilet"],
        category: "meat",
      },
      {
        name: "Rejer",
        quantity: "150 g",
        searchTerms: ["rejer", "tigerrejer"],
        category: "frozen",
      },
      {
        name: "Æg",
        quantity: "4 stk",
        searchTerms: ["æg", "frilandsæg"],
        category: "dairy",
      },
      {
        name: "Løg",
        quantity: "1 stk",
        searchTerms: ["løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Rød chili",
        quantity: "2 stk",
        searchTerms: ["rød chili", "chili"],
        category: "produce",
      },
      {
        name: "Sojasauce",
        quantity: "3 spsk",
        searchTerms: ["sojasauce", "soja"],
        category: "pantry",
      },
      {
        name: "Ketjap manis",
        quantity: "2 spsk",
        searchTerms: ["ketjap manis", "sød soja"],
        category: "pantry",
      },
      {
        name: "Sesamolie",
        quantity: "1 spsk",
        searchTerms: ["sesamolie"],
        category: "pantry",
      },
      {
        name: "Agurk",
        quantity: "0.5 stk",
        searchTerms: ["agurk"],
        category: "produce",
      },
      {
        name: "Forårsløg",
        quantity: "3 stk",
        searchTerms: ["forårsløg", "grønne løg"],
        category: "produce",
      },
      {
        name: "Neutral olie",
        quantity: "3 spsk",
        searchTerms: ["rapsolie", "solsikkeolie"],
        category: "pantry",
      },
    ],
  },
  {
    name: "Chow Mein",
    servings: 4,
    complexity: "quick",
    cuisineType: "asian",
    proteinType: "pork",
    ingredients: [
      {
        name: "Ægnudler",
        quantity: "300 g",
        searchTerms: ["ægnudler", "nudler", "wok nudler"],
        category: "pantry",
      },
      {
        name: "Svinekød i strimler",
        quantity: "300 g",
        searchTerms: ["svinekød", "svinemørbrad", "nakkefilet"],
        category: "meat",
      },
      {
        name: "Spidskål",
        quantity: "200 g",
        searchTerms: ["spidskål", "kål"],
        category: "produce",
      },
      {
        name: "Gulerødder",
        quantity: "2 stk",
        searchTerms: ["gulerødder", "gulerod"],
        category: "produce",
      },
      {
        name: "Rød peberfrugt",
        quantity: "1 stk",
        searchTerms: ["peberfrugt", "rød peberfrugt"],
        category: "produce",
      },
      {
        name: "Forårsløg",
        quantity: "4 stk",
        searchTerms: ["forårsløg", "grønne løg"],
        category: "produce",
      },
      {
        name: "Hvidløg",
        quantity: "3 fed",
        searchTerms: ["hvidløg"],
        category: "produce",
      },
      {
        name: "Ingefær",
        quantity: "1 tsk",
        searchTerms: ["ingefær", "frisk ingefær"],
        category: "produce",
      },
      {
        name: "Sojasauce",
        quantity: "3 spsk",
        searchTerms: ["sojasauce", "soja"],
        category: "pantry",
      },
      {
        name: "Østerssauce",
        quantity: "2 spsk",
        searchTerms: ["østerssauce", "oyster sauce"],
        category: "pantry",
      },
      {
        name: "Sesamolie",
        quantity: "1 spsk",
        searchTerms: ["sesamolie"],
        category: "pantry",
      },
      {
        name: "Neutral olie",
        quantity: "3 spsk",
        searchTerms: ["rapsolie", "solsikkeolie"],
        category: "pantry",
      },
    ],
  },
];
